# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: ohana_shop_development

test:
  <<: *default
  database: ohana_shop_test

production:
  primary:
    <<: *default
    database: ohana_shop_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: ohana_shop_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: ohana_shop_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: ohana_shop_production_cable
    migrations_paths: db/cable_migrate
